<?php

declare(strict_types=1);

namespace IGS\Ecommerce\Helper;

final class CountryFlags
{
    /** @var array<string, string> nome paese (lowercase) => flag emoji */
    private const MAP = [
        'italia' => '🇮🇹',
        'italy' => '🇮🇹',
        'portogallo' => '🇵🇹',
        'portugal' => '🇵🇹',
        'irlanda' => '🇮🇪',
        'ireland' => '🇮🇪',
        'francia' => '🇫🇷',
        'france' => '🇫🇷',
        'spagna' => '🇪🇸',
        'spain' => '🇪🇸',
        'regno unito' => '🇬🇧',
        'united kingdom' => '🇬🇧',
        'uk' => '🇬🇧',
        'inghilterra' => '🇬🇧',
        'england' => '🇬🇧',
        'germania' => '🇩🇪',
        'germany' => '🇩🇪',
        'grecia' => '🇬🇷',
        'greece' => '🇬🇷',
        'paesi bassi' => '🇳🇱',
        'netherlands' => '🇳🇱',
        'olanda' => '🇳🇱',
        'svizzera' => '🇨🇭',
        'switzerland' => '🇨🇭',
        'austria' => '🇦🇹',
        'turchia' => '🇹🇷',
        'turkey' => '🇹🇷',
        'croazia' => '🇭🇷',
        'croatia' => '🇭🇷',
        'slovenia' => '🇸🇮',
        'malta' => '🇲🇹',
        'azzorre' => '🇵🇹',
        'azores' => '🇵🇹',
        'scozia' => '🇬🇧',
        'scotland' => '🇬🇧',
        'belgio' => '🇧🇪',
        'belgium' => '🇧🇪',
        'polonia' => '🇵🇱',
        'poland' => '🇵🇱',
        'repubblica ceca' => '🇨🇿',
        'czech republic' => '🇨🇿',
        'cekia' => '🇨🇿',
        'czechia' => '🇨🇿',
        'ungheria' => '🇭🇺',
        'hungary' => '🇭🇺',
        'romania' => '🇷🇴',
        'romenia' => '🇷🇴',
        'bulgaria' => '🇧🇬',
        'serbia' => '🇷🇸',
        'bosnia' => '🇧🇦',
        'bosnia ed erzegovina' => '🇧🇦',
        'bosnia and herzegovina' => '🇧🇦',
        'montenegro' => '🇲🇪',
        'albania' => '🇦🇱',
        'macedonia' => '🇲🇰',
        'north macedonia' => '🇲🇰',
        'macedonia del nord' => '🇲🇰',
        'ucraina' => '🇺🇦',
        'ukraine' => '🇺🇦',
        'russia' => '🇷🇺',
        'norvegia' => '🇳🇴',
        'norway' => '🇳🇴',
        'svezia' => '🇸🇪',
        'sweden' => '🇸🇪',
        'danimarca' => '🇩🇰',
        'denmark' => '🇩🇰',
        'finlandia' => '🇫🇮',
        'finland' => '🇫🇮',
        'islanda' => '🇮🇸',
        'iceland' => '🇮🇸',
        'estonia' => '🇪🇪',
        'lettonia' => '🇱🇻',
        'latvia' => '🇱🇻',
        'lituania' => '🇱🇹',
        'lithuania' => '🇱🇹',
        'andorra' => '🇦🇩',
        'monaco' => '🇲🇨',
        'san marino' => '🇸🇲',
        'vaticano' => '🇻🇦',
        'città del vaticano' => '🇻🇦',
        'lisbona' => '🇵🇹',
        'lisbon' => '🇵🇹',
        'madeira' => '🇵🇹',
        'madera' => '🇵🇹',
        'sardegna' => '🇮🇹',
        'sardinia' => '🇮🇹',
        'sicilia' => '🇮🇹',
        'sicily' => '🇮🇹',
        'toscana' => '🇮🇹',
        'tuscany' => '🇮🇹',
        'liguria' => '🇮🇹',
        'provence' => '🇫🇷',
        'provenza' => '🇫🇷',
        'loira' => '🇫🇷',
        'loire' => '🇫🇷',
        'normandia' => '🇫🇷',
        'normandy' => '🇫🇷',
        'catalogna' => '🇪🇸',
        'catalonia' => '🇪🇸',
        'andalusia' => '🇪🇸',
        'israele' => '🇮🇱',
        'israel' => '🇮🇱',
        'emirati arabi uniti' => '🇦🇪',
        'uae' => '🇦🇪',
        'emirates' => '🇦🇪',
        'marocco' => '🇲🇦',
        'morocco' => '🇲🇦',
        'egitto' => '🇪🇬',
        'egypt' => '🇪🇬',
        'tunisia' => '🇹🇳',
        'giappone' => '🇯🇵',
        'japan' => '🇯🇵',
        'cina' => '🇨🇳',
        'china' => '🇨🇳',
        'india' => '🇮🇳',
        'thailandia' => '🇹🇭',
        'thailand' => '🇹🇭',
        'vietnam' => '🇻🇳',
        'indonesia' => '🇮🇩',
        'bali' => '🇮🇩',
        'sri lanka' => '🇱🇰',
        'australia' => '🇦🇺',
        'nuova zelanda' => '🇳🇿',
        'new zealand' => '🇳🇿',
        'stati uniti' => '🇺🇸',
        'usa' => '🇺🇸',
        'stati uniti d\'america' => '🇺🇸',
        'united states' => '🇺🇸',
        'canada' => '🇨🇦',
        'messico' => '🇲🇽',
        'mexico' => '🇲🇽',
        'brasile' => '🇧🇷',
        'brazil' => '🇧🇷',
        'argentina' => '🇦🇷',
        'perù' => '🇵🇪',
        'peru' => '🇵🇪',
        'cile' => '🇨🇱',
        'chile' => '🇨🇱',
        'colombia' => '🇨🇴',
        'sudafrica' => '🇿🇦',
        'south africa' => '🇿🇦',
        'kenya' => '🇰🇪',
        'tanzania' => '🇹🇿',
    ];

    public static function forName(string $name): ?string
    {
        $key = mb_strtolower(trim($name));
        if ($key === '') {
            return null;
        }
        return self::MAP[$key] ?? null;
    }

    public static function withFlag(string $name): string
    {
        // Le flag-emoji non sono renderizzate su Windows (mostrerebbero "IE", "ES", ...):
        // restituiamo il solo nome del paese per una resa uniforme su tutti i sistemi.
        return $name;
    }
}
